apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: plumb
  labels:
    app.kubernetes.io/name: plumb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plumb
